### ISSUE TITLE
[Feature Request] New component request "Toast Message"

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2180]
A component should be made to notify the user while navigating on the grid or navigating on the tabs or doing any operation. W2alert can be used to notify an incoming message from the server, but this interrupts the user's current action. Imagine an information bubble on the right side of the screen that informs but does not affect the user. I wanted to share this opinion of mine, whether it should be added to the library or not is up to you. thanks.

**Comment by vitmalina** [comment]
What about events. Do this for the grid
```js
grid.on('*', e => console.log(e))
```
it will show all what is happening with the grid. 

Is it sufficient for your use case?

**Comment by mansurdegirmenci** [comment]
I wanted it for the user, not for me :) first of all, nice information, thank you. Let's think about an information like this, in the past, there was Windows Live Messenger, when a person logged in, we would get a message that the user is logged in at the bottom right. the user would be notified. Let's consider such a situation. w2alert is nice, but it wouldn't make sense for it to warn that witmalina has logged in while I'm updating the list and stop my update :) I wanted to say that.

**Comment by mpf82** [comment]
I think @mansurdegirmenci  is requesting a "toast message" component - correct?

https://www.google.com/search?q=toast+js&tbm=isch

https://www.jqueryscript.net/blog/Best-Toast-Notification-jQuery-Plugins.html

**Comment by mansurdegirmenci** [comment]
yes "toast" is correct. I meant something like this. 

![image](https://user-images.githubusercontent.com/38755096/147829539-a1504e39-2cf3-48b0-8b0d-83753b02bb31.png)

**Comment by vitmalina** [comment]
I have little use for the toast messages. They feel too noisy for me.

I did have some message on the bottom, like black message in gmail. They were useful, and easy to do. Might add to w2utils, something like this
```js
function message(options) {
        return new Promise((resolve, reject) => {
            if (typeof options == 'string') {
                options = { text: options }
            }
            options = options || {}
            options.timeout = options.timeout || 25000 // 25 secodns or will be hidden on route change
            $('#canvas-box').parent().find('#app-message').remove()
            if (typeof app.main.msgResolve == 'function') {
                app.main.msgResolve()
            }
            app.main.msgResolve = resolve
            clearTimeout(app.utils._last_message)
            if (options.text) {
                let html = `
                    <div id="app-message">
                        <div ${options.error ? 'class="error-app-msg"' : ''}>
                            ${options.text}
                            ${options.link ? `<a class="message-link">${options.link}</a>` : ''}
                            <span class="close icon-cross2"></span>
                        </div>
                    </div>`
                $('#canvas-box').parent().append(html)
                $('#app-message .close')
                    .on('click', (event) => {
                        $('#app-message').remove()
                        resolve()
                    })
                if (options.function) {
                    $('#app-message .message-link')
                        .on('click', () => {
                            options.function()
                            $('#canvas-box').parent().find('#app-message').remove()
                            resolve()
                        })
                }
                app.utils._last_message = setTimeout(() => {
                    $('#canvas-box').parent().find('#app-message').remove()
                    resolve()
                }, options.timeout)
            }
        })
    }
```
with css
```less
#app-message {
    position: absolute;
    display: flex;
    flex-direction: column;
    align-items: center;
    user-select: none;
    left: 0px;
    right: 0px;
    bottom: 20px;
    z-index: 10000;
    overflow: hidden;
    > div {
        position: relative;
        background-color: #292828ba;
        color: #ffffff;
        padding: 8px 44px 8px 16px;
        border-radius: 4px;
        box-shadow: 3px 3px 10px #9c9c9c;
        max-height: 76px;
        min-width: 100px;
        max-width: 800px;
        font-size: 13px;
        a {
            color: #40c5e4!important;
            text-decoration: underline;
        }
        a:hover {
            color: #02a0c4!important;
            cursor: pointer;
        }
        > span {
            padding: 4px 6px;
            border-radius: 3px;
            font-size: 12px;
            color: #c3c3c3;
            position: absolute;
            right: 5px;
            top: 3px;
        }
        > span:hover {
            background-color: #807e7e;
            color: #ffffff;
        }
    }
}
```
