### ISSUE TITLE
W2Grid : some rows are not equals

### ISSUE THREAD

**Issue by lucastucious** [vitmalina/w2ui#2390]
### **Short description**
I've added some css to enable word wrap but if it works fine on table, select and row line are not in the same div so can't follow : 
![image](https://user-images.githubusercontent.com/28046122/223179885-f9290fdd-29e4-4bea-9306-e2ce286e601d.png)

css code for reference : 
```css
  .w2ui-grid-data {
  color:black;
  word-wrap: normal;
  } 

  .w2ui-grid .w2ui-grid-body table td.w2ui-grid-data>div{
    overflow: visible;
    white-space:break-spaces;
  }
```

### **What is desired behavior**
May the select rows should be in the same table ?

### **Infos**
w2ui 2.0
chrome 110.0.548
